# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/service_container.html
parameters:
    #parameter_name: value

services:
    app.form.registration:
            class: ready4sBundle\Form\RegistrationType
            tags:
                - { name: form.type, alias: app_user_registration }



    fos.registration_confirm:
        class: ready4sBundle\EventListener\RegistrationConfirmListener
        arguments: ['@router']
        tags:
            - { name: kernel.event_subscriber }

